services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: online_vina
      POSTGRES_USER: annguyen
      POSTGRES_PASSWORD: SkXbMhUsK5jeCLTi
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - appnet

  adminer:
    image: adminer
    container_name: db-adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '8081:8080'
    networks:
      - appnet

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: device-app
    depends_on:
      db:
        condition: service_started
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://annguyen:SkXbMhUsK5jeCLTi@db:5432/online_vina?schema=public
    ports:
      - '3000:3000'
    command: sh -lc "yarn prisma migrate deploy && node dist/main.js"
    networks:
      - appnet

volumes:
  pgdata: {}

networks:
  appnet: {}
